#!/usr/bin/env bash

setup_remote () {
    name=$1
    url=$2

    echo ""
    echo "setup remote \"$name\" -> $url"
    git remote rm $name 2> /dev/null
    git remote add $name $url
    git fetch $name
}

setup_remote "production" "zope@example.server.ch:/home/zope/01-plone.ch"

cd $(dirname "$0")/..
ln -s var/log
mkdir tmp
cd tmp
echo "*" > .gitignore
echo "!.gitignore" >> .gitignore
